### PR TITLE
WIP Write Ahead Log

### PR DESCRIPTION
**Pull request by dranikpg**
I've built a seemingly working and effective (I'm getting up to x10 speed) WAL implementation, but there are still issues left to resolve/discuss that I'll take up in the coming days

#165

### CODE REVIEW

**Comment by dranikpg** [comment]
One current issue is having multiple operations on the same document in one batch. Deletes after creates don't work. Updates after creates are hard to manage (requires keeping track of the shard). Updates after deletes re-create the document but really shouldn't.
Becase all CUD (Create, Update, Delete) operations change _the whole_ document, multiple operations can be merged into just a single one. For example, in case of multiple updates only the last one matter. A _Create-Update-Update_ chain can be transformed into a single _Create_ with the data from the latest update. Any updates after a delete should be discarded. 

Besides that, those merged operations should be _idempotent_. This is generally a requirement of WAL operations, becase we could crash after performing all logged operations, but just before storing the confirmation of this having happened. Updates/Deletes are no problem, but consecutive Creates should not add new entries. Instead they should check whether their id is already in the index. 

So one has to carefully map handler actions to strictly defined log operations. There are separately _Creates_, _Updates_ and _Updates-With-Insertions_.

**Comment by hengfeiyang** [comment]
👍🏻 @dranikpg, Your work is great, and i'm implement WAL too in my own branch. I think i should let you know.

**Comment by dranikpg** [comment]
Oh, sorry. It hadn't been pointed out anywhere in the issue. I'll close mine in this case

**Comment by hengfeiyang** [comment]
Thanks for that, your work is great.

**Pull request closed without merging**
